substitutions:
  name: ${name}
  friendly_name: ${friendly_name}
  device_description: "Deye Inverter"
  modbus_controller_id: deye_modbus_controller
  baud_rate: "9600"
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "100" # Amps
  default_max_sell_power: "6000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"
  default_force_off_grid: "off" # "on", "off"

packages:
  init: !include packages/init.yaml
  battery: !include packages/deye_hybrid_1p/battery.yaml
  gen: !include packages/deye_hybrid_1p/gen.yaml
  grid: !include packages/deye_hybrid_1p/grid.yaml
  load: !include packages/deye_hybrid_1p/load.yaml
  work_mode: !include packages/deye_hybrid_1p/work_mode.yaml
  device: !include packages/deye_hybrid_1p/device.yaml
  inverter: !include packages/deye_hybrid_1p/inverter.yaml
  pv: !include packages/deye_hybrid_1p/pv.yaml
  tou: !include packages/deye_hybrid_1p/tou.yaml


